# Generated by Django 4.2.5 on 2025-02-02 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_type', models.CharField(blank=True, choices=[('tax deed', 'Tax Deed'), ('tax lien', 'Tax Lien')], default='', max_length=10, null=True)),
                ('is_online', models.TextField(blank=True, choices=[('online', 'Online'), ('in-person', 'In-person')], default='', max_length=10, null=True)),
                ('property_type', models.TextField(blank=True, default='', null=True)),
                ('Market_Land_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Market_Land_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Market_Improvement_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Market_Improvement_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Market_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Market_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Assessed_Land_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Assessed_Land_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Assessed_Improvement_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Assessed_Improvement_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Assessed_Value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Assessed_Value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('face_value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('face_value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('states', models.ManyToManyField(blank=True, to='criterion.states')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
