# Generated by Django 5.1.2 on 2024-11-07 17:11

from django.db import migrations, models


def populate_states(apps, schema_editor):
    States = apps.get_model('criterion', 'States')
    states_data = [
        {"state": "Alabama", "abbreviation": "AL"},
        {"state": "Alaska", "abbreviation": "AK"},
        {"state": "Arizona", "abbreviation": "AZ"},
        {"state": "Arkansas", "abbreviation": "AR"},
        {"state": "California", "abbreviation": "CA"},
        {"state": "Colorado", "abbreviation": "CO"},
        {"state": "Connecticut", "abbreviation": "CT"},
        {"state": "Delaware", "abbreviation": "DE"},
        {"state": "District of Columbia", "abbreviation": "DC"},
        {"state": "Florida", "abbreviation": "FL"},
        {"state": "Georgia", "abbreviation": "GA"},
        {"state": "Hawaii", "abbreviation": "HI"},
        {"state": "Idaho", "abbreviation": "ID"},
        {"state": "Illinois", "abbreviation": "IL"},
        {"state": "Indiana", "abbreviation": "IN"},
        {"state": "Iowa", "abbreviation": "IA"},
        {"state": "Kansas", "abbreviation": "KS"},
        {"state": "Kentucky", "abbreviation": "KY"},
        {"state": "Louisiana", "abbreviation": "LA"},
        {"state": "Maine", "abbreviation": "ME"},
        {"state": "Maryland", "abbreviation": "MD"},
        {"state": "Massachusetts", "abbreviation": "MA"},
        {"state": "Michigan", "abbreviation": "MI"},
        {"state": "Minnesota", "abbreviation": "MN"},
        {"state": "Mississippi", "abbreviation": "MS"},
        {"state": "Missouri", "abbreviation": "MO"},
        {"state": "Montana", "abbreviation": "MT"},
        {"state": "Nebraska", "abbreviation": "NE"},
        {"state": "Nevada", "abbreviation": "NV"},
        {"state": "New Hampshire", "abbreviation": "NH"},  # no tax sales
        {"state": "New Jersey", "abbreviation": "NJ"},
        {"state": "New Mexico", "abbreviation": "NM"},
        {"state": "New York", "abbreviation": "NY"},
        {"state": "North Carolina", "abbreviation": "NC"},
        {"state": "North Dakota", "abbreviation": "ND"},
        {"state": "Ohio", "abbreviation": "OH"},
        {"state": "Oklahoma", "abbreviation": "OK"},
        {"state": "Oregon", "abbreviation": "OR"},
        {"state": "Pennsylvania", "abbreviation": "PA"},
        {"state": "Rhode Island", "abbreviation": "RI"},
        {"state": "South Carolina", "abbreviation": "SC"},
        {"state": "South Dakota", "abbreviation": "SD"},
        {"state": "Tennessee", "abbreviation": "TN"},
        {"state": "Texas", "abbreviation": "TX"},
        {"state": "Utah", "abbreviation": "UT"},
        {"state": "Vermont", "abbreviation": "VT"},
        {"state": "Virginia", "abbreviation": "VA"},
        {"state": "Washington", "abbreviation": "WA"},
        {"state": "West Virginia", "abbreviation": "WV"},
        {"state": "Wisconsin", "abbreviation": "WI"},
        {"state": "Wyoming", "abbreviation": "WY"},
    ]

    for state_data in states_data:
        States.objects.create(**state_data)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies for the initial migration
    ]
    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.RunPython(populate_states),
    ]