# Generated by Django 5.1.2 on 2024-11-24 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_type', models.CharField(blank=True, choices=[('tax deed', 'Tax Deed'), ('tax lien', 'Tax Lien')], default='', max_length=10, null=True)),
                ('is_online', models.TextField(blank=True, choices=[('online', 'Online'), ('in-person', 'In-person')], default='', max_length=10, null=True)),
                ('goal', models.CharField(blank=True, choices=[('interest', 'Interest'), ('foreclosure', 'Foreclosure')], default='', max_length=15, null=True)),
                ('property_type', models.TextField(blank=True, default='', null=True)),
                ('market_value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('face_value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('face_value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('states', models.ManyToManyField(blank=True, to='criterion.states')),
            ],
        ),
    ]
