# Generated by Django 3.0.4 on 2024-11-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_password_reset_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
