# Generated by Django 3.0.4 on 2024-11-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_is_password_reset_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_password_reset_confirmed',
        ),
    ]
