# Generated by Django 3.0.4 on 2024-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userprofile_is_password_reset_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_password_reset_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
