# Generated by Django 5.1.2 on 2024-12-18 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_remove_auction_bankruptcy_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('my_bid_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Bid', 'Bid'), ('Won', 'Won'), ('Foreclosed', 'Foreclosed'), ('Archived', 'Archived')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('auction_authority', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('amount_in_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('auction_start', models.DateField(blank=True, null=True)),
                ('auction_end', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
            },
        ),
    ]
