# Generated by Django 4.2.5 on 2025-02-02 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('auction_authority', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('amount_in_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('auction_start', models.DateField(blank=True, null=True)),
                ('auction_end', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('sort_no', models.CharField(blank=True, max_length=50)),
                ('bankruptcy_flag', models.BooleanField(default=False)),
                ('parcel_number', models.CharField(blank=True, max_length=50)),
                ('property_class', models.CharField(blank=True, max_length=255)),
                ('tax_overdue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accessed_land_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accessed_improvement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('zillow_link', models.URLField(blank=True, max_length=255, null=True)),
                ('redfin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('Market_Land_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Market_Improvement_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Total_Market_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('lot_size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('building_size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedroom_number', models.IntegerField(blank=True, null=True)),
                ('bathroom_number', models.IntegerField(blank=True, null=True)),
                ('nearby_schools', models.CharField(blank=True, max_length=255, null=True)),
                ('walk_score', models.IntegerField(blank=True, null=True)),
                ('transit_score', models.IntegerField(blank=True, null=True)),
                ('bike_score', models.IntegerField(blank=True, null=True)),
                ('environmental_hazard_status', models.CharField(blank=True, max_length=100, null=True)),
                ('flood_status', models.CharField(blank=True, max_length=100, null=True)),
                ('flood_risk', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_sale_date', models.DateField(blank=True, null=True)),
                ('latest_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('my_bid_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Bid', 'Bid'), ('Won', 'Won'), ('Foreclosed', 'Foreclosed'), ('Archived', 'Archived')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
            },
        ),
    ]
