# Generated by Django 4.2.5 on 2025-02-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_type', models.CharField(choices=[('lien', 'Lien'), ('deed', 'Deed')], max_length=20)),
                ('is_online', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-person')], max_length=20)),
                ('auction_tax_year', models.IntegerField(blank=True, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('auction_start', models.DateField(blank=True, null=True)),
                ('auction_end', models.DateField(blank=True, null=True)),
                ('redemption_period', models.IntegerField(blank=True, null=True)),
                ('foreclosure_date', models.DateField(blank=True, null=True)),
                ('authority_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_4', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_5', models.CharField(blank=True, max_length=20, null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_4', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_5', models.EmailField(blank=True, max_length=254, null=True)),
                ('Homestead_Exemptions', models.BooleanField(blank=True, max_length=255, null=True)),
                ('primary_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(max_length=50)),
                ('sort_no', models.CharField(max_length=50)),
                ('bankruptcy_flag', models.BooleanField(default=False)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('parcel_number', models.CharField(max_length=50)),
                ('property_class', models.CharField(max_length=255)),
                ('tax_overdue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accessed_land_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accessed_improvement_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_assessed_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount_annual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zillow_link', models.URLField(blank=True, max_length=255, null=True)),
                ('redfin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('Market_Land_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Market_Improvement_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Total_Market_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('year_built', models.IntegerField()),
                ('lot_size_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_size_acres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('building_size_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedroom_number', models.IntegerField()),
                ('bathroom_number', models.IntegerField()),
                ('nearby_schools', models.CharField(blank=True, max_length=255, null=True)),
                ('walk_score', models.IntegerField(blank=True, null=True)),
                ('transit_score', models.IntegerField(blank=True, null=True)),
                ('bike_score', models.IntegerField(blank=True, null=True)),
                ('environmental_hazard_status', models.CharField(blank=True, max_length=100, null=True)),
                ('flood_status', models.CharField(blank=True, max_length=100, null=True)),
                ('flood_risk', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_sale_date', models.DateField(blank=True, null=True)),
                ('latest_sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foreclose_score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifier', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.auction')),
                ('owners', models.ManyToManyField(related_name='properties', to='property.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_due_date', models.DateField(blank=True, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='property.property')),
            ],
        ),
    ]
